// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQbPRjLAg_GkE9495Rn3OZmge27A7W9k',
    appId: '1:504131612092:web:e4bb59b2f0e2a617990fb9',
    messagingSenderId: '504131612092',
    projectId: 'food-trucks-ca748',
    authDomain: 'food-trucks-ca748.firebaseapp.com',
    storageBucket: 'food-trucks-ca748.appspot.com',
    measurementId: 'G-2YRNF9BL7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQl-wS-vPWWzOs_J4wZUE82_SBqP7d_q8',
    appId: '1:504131612092:android:746ec0c8ab0be379990fb9',
    messagingSenderId: '504131612092',
    projectId: 'food-trucks-ca748',
    storageBucket: 'food-trucks-ca748.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3uPGmkIbTpr2dMzk-x0GAVJB0Nb8F2U',
    appId: '1:504131612092:ios:afe6a1b038c64ec2990fb9',
    messagingSenderId: '504131612092',
    projectId: 'food-trucks-ca748',
    storageBucket: 'food-trucks-ca748.appspot.com',
    iosBundleId: 'com.kjbn.departuretimes.departuretimes',
  );
}
